<?php

namespace App\Support\Tenancy;

use App\Models\Tenant;
use App\Support\Locale\Calendars;

/**
 * The tenant the current request (or job) acts for.
 *
 * Everything tenant-scoped reads from here rather than from the authenticated user, because the
 * same scoping must hold for API-key callers, queued jobs and console commands, none of which
 * have a logged-in user.
 */
class TenantContext
{
    private ?Tenant $tenant = null;

    /** Set to true only inside deliberate cross-tenant work (system jobs, admin tooling). */
    private bool $unscoped = false;

    public function set(?Tenant $tenant): void
    {
        $this->tenant = $tenant;

        /*
         * Binding an account also binds the calendar it keeps its dates in.
         *
         * Here rather than at every call site, because the places that need it are the ones nobody
         * remembers: a report generated by a queue worker, a confirmation sent an hour after the
         * request that caused it, a console command run at four in the morning. None of those has a
         * request to read a setting from, and all of them have an account.
         *
         * A hosted site overrides this with its own — see ResolveSiteFromHost — because what a
         * buyer reads and what the box office types are two different decisions.
         */
        Calendars::use($tenant?->calendar);
    }

    public function get(): ?Tenant
    {
        return $this->tenant;
    }

    public function id(): ?string
    {
        return $this->tenant?->id;
    }

    public function has(): bool
    {
        return $this->tenant !== null;
    }

    public function idOrFail(): string
    {
        if ($this->tenant === null) {
            throw new \RuntimeException('No tenant is bound to the current context.');
        }

        return $this->tenant->id;
    }

    public function isUnscoped(): bool
    {
        return $this->unscoped;
    }

    /**
     * Run a callback outside tenant scoping. Use sparingly and never on a path reachable by a
     * tenant-authenticated request — this deliberately disables the isolation guarantee.
     */
    public function runUnscoped(callable $callback): mixed
    {
        $previous = $this->unscoped;
        $this->unscoped = true;

        try {
            return $callback();
        } finally {
            $this->unscoped = $previous;
        }
    }

    /** Run a callback as a specific tenant, restoring the previous binding afterwards. */
    public function runAs(?Tenant $tenant, callable $callback): mixed
    {
        $previous = $this->tenant;
        // Restored with the tenant, so a run of a hundred confirmations for four venues does not
        // leave the fourth venue's calendar on the fifth.
        $calendar = Calendars::chosen();

        $this->set($tenant);

        try {
            return $callback();
        } finally {
            $this->tenant = $previous;
            Calendars::use($calendar);
        }
    }
}
