import { chromium } from 'playwright';
const browser = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium-1194/chrome-linux/chrome' });
const page = await browser.newPage({ viewport: { width: 1600, height: 950 } });
const errors = [];
page.on('pageerror', e => errors.push(e.message));
page.on('console', m => { if (m.type() === 'error') errors.push(m.text()); });

await page.goto('http://127.0.0.1:8123', { waitUntil: 'networkidle' });
await page.fill('input[name=email]', 'owner@northgate.test');
await page.fill('input[name=password]', 'password');
await page.click('#login button[type=submit]');
await page.waitForSelector('.topbar');
await page.click('nav button[data-view=maps]');
await page.waitForSelector('button[data-map]');
await page.click('button[data-map]');
await page.waitForSelector('#dz-canvas');
await page.waitForTimeout(1200);
await page.screenshot({ path: '/tmp/designer.png' });
console.log('errors:', errors.length ? errors.join(' | ') : 'none');
console.log('places:', await page.locator('.insp-places').first().innerText().catch(() => 'n/a'));
const checks = await page.locator('.insp-check').allInnerTexts();
console.log('checks:', JSON.stringify(checks));
await browser.close();
